[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-xresources3
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-xresources3
GtkTheme=oomox-xresources3
IconTheme=oomox-xresources3
MetacityTheme=oomox-xresources3
