#!/bin/bash
center=false
for arg in "$@"
do
  if [ "$arg" == "home" ] || [ "$arg" == "h" ]
  then
    echo "Initializing home config..."
    /bin/bash /home/om/.screenlayout/drt1.sh 
  elif [ "$arg" == "--center" ] || [ "$arg" == "c" ]
  then
    center=true
  elif [ "$arg" == "--joshdesk" ] || [ "$arg" == "j" ]
  then
    echo "Initializing josh's desk config..."
    /bin/bash /home/om/.screenlayout/josh-desk.sh 
  fi
done
echo "Initializing ricey goodness..."
nohup wal -R &
exec nohup polyset.sh &
