#!/bin/bash
center=false
for arg in "$@"
do
  if [ "$arg" == "home" ] || [ "$arg" == "h" ]
  then
    echo "Initializing home config..."
    /bin/bash /home/om/.screenlayout/origami-table.sh 
  elif [ "$arg" == "--center" ] || [ "$arg" == "-c" ]
  then
    center=true
  fi
done
echo "Initializing ricey goodness..."
if [ "$center" = true ]
then
  wllppr center &
else
  wllppr &
fi
nohup wal -R -n &
exec nohup polyset.sh &
