#!/bin/bash
center=false
for arg in "$@"
do
  if [ "$arg" == "home" ] || [ "$arg" == "h" ]
  then
    echo "Initializing home config..."
    /bin/bash /home/om/.screenlayout/Ithaca_2.sh
  elif [ "$arg" == "--center" ] || [ "$arg" == "c" ]
  then
    center=true
  elif [ "$arg" == "xcog" ] || [ "$arg" == "x" ]
  then
    echo "Initializing lab conference room config..."
    /bin/bash /home/om/.screenlayout/xcog-1.sh
  elif [ "$arg" == "lab" ] || [ "$arg" == "l" ]
  then
    echo "Initializing lab desk config..."
    /bin/bash /home/om/.screenlayout/lab-1.sh
  fi
done
echo "Initializing ricey goodness..."
nohup wal -R &
wllppr &
exec nohup polyset.sh &
