#! /bin/sh

polyset.sh &

tabbed -r 2 st -w '' &

sxhkd &
 . "${HOME}/.cache/wal/colors.sh"

bspc monitor LVDS-1 -d 1 2 3 4 5 6 7
bspc config border_width 4
bspc config window_gap 0
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding	0
bspc config right_padding	0

bspc config presel_feedback_color "$color13"
bspc config normal_border_color "$background"
bspc config active_border_color "$background"
bspc config focused_border_color "$color4"
bspc config split_ratio 0.6
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc config pointer_motion_interval 7

bspc rule -a Gimp desktop=^4 state=floating follow=on
bspc rule -a Firefox desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Chromium border_width=0
bspc rule -a RStudio border_width=0
bspc rule -a libreoffice-startcenter desktop=^3
bspc rule -a Pavucontrol desktop=^7
bspc rule -a Spotify desktop=^6
bspc rule -a Discord desktop=^5
