#! /bin/sh

 sxhkd &
 . "${HOME}/.cache/wal/colors.sh"

bspc monitor -d I II III IV V VI VII

bspc config border_width 3
bspc config window_gap 0
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding	0
bspc config right_padding	0

bspc config presel_feedback_color "$color2"
bspc config normal_border_color "$background"
bspc config active_border_color "$color3"
bspc config focused_border_color "$color3"
bspc config split_ratio 0.6
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a * floating=on
bspc rule -a * state=floating
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a LibreOffice desktop='^4'
bspc rule -a LibreOffice state=floating
bspc rule -a Spotify desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a st state=tiled
bspc rule -a zathura state=tiled
bspc rule -a Chromium border_width=0
bspc rule -a RStudio border_width=0
bspc rule -a URxvt:urxvt_keys_help state=floating
