--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/om/media/pics/wall/koi.jpg"

-- Special
background="#efeff4"
foreground="#3e3e3e"
cursor="#3e3e3e"

-- Colors
color0="#efeff4"
color1="#b32530"
color2="#447a67"
color3="#b68b59"
color4="#1789a7"
color5="#7a9ca9"
color6="#b32536"
color7="#3e3e3e"
color8="#3e3e3e"
color9="#b32530"
color10="#447a67"
color11="#b68b59"
color12="#1789a7"
color13="#7a9ca9"
color14="#b32536"
color15="#3e3e3e"
