--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/om/media/pics/wall/mitani-curves.jpg"

-- Special
background="#efeff4"
foreground="#3e3e3e"
cursor="#7a9ca9"

-- Colors
color0="#efeff4"
color1="#bf616A"
color2="#639986"
color3="#D08770"
color4="#5e81ac"
color5="#7a9ca9"
color6="#B48EAD"
color7="#3e3e3e"
color8="#3e3e3e"
color9="#bf616A"
color10="#639986"
color11="#D08770"
color12="#5e81ac"
color13="#7a9ca9"
color14="#B48EAD"
color15="#7a9ca9"
