--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/om/media/pics/wall/joel.jpg"

-- Special
background="#3f3f3f"
foreground="#dcdccc"
cursor="#cc9393"

-- Colors
color0="#3f3f3f"
color1="#cc9393"
color2="#7f9f7f"
color3="#d0bf8f"
color4="#6ca0a3"
color5="#dc8cc3"
color6="#93e0e3"
color7="#dcdccc"
color8="#828282"
color9="#cc9393"
color10="#7f9f7f"
color11="#d0bf8f"
color12="#6ca0a3"
color13="#dc8cc3"
color14="#93e0e3"
color15="#dcdccc"
