# Shell variables
# Generated by 'wal'
wallpaper='/home/om/media/pics/wall/mitani-curves.jpg'

# Special
background='#efeff4'
foreground='#3e3e3e'
cursor='#7a9ca9'

# Colors
color0='#efeff4'
color1='#bf616A'
color2='#447a67'
color3='#D08770'
color4='#5e81ac'
color5='#7a9ca9'
color6='#B48EAD'
color7='#3e3e3e'
color8='#3e3e3e'
color9='#bf616A'
color10='#447a67'
color11='#D08770'
color12='#5e81ac'
color13='#7a9ca9'
color14='#B48EAD'
color15='#7a9ca9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
