# Shell variables
# Generated by 'wal'
wallpaper='/home/om/media/pics/wall/koi.jpg'

# Special
background='#efeff4'
foreground='#3e3e3e'
cursor='#3e3e3e'

# Colors
color0='#efeff4'
color1='#b32530'
color2='#447a67'
color3='#b68b59'
color4='#1789a7'
color5='#7a9ca9'
color6='#b32536'
color7='#3e3e3e'
color8='#3e3e3e'
color9='#b32530'
color10='#447a67'
color11='#b68b59'
color12='#1789a7'
color13='#7a9ca9'
color14='#b32536'
color15='#3e3e3e'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
