# Shell variables
# Generated by 'wal'
wallpaper='/home/om/media/pics/wall/cat.jpg'

# Special
background='#070F0D'
foreground='#b1bcbd'
cursor='#b1bcbd'

# Colors
color0='#070F0D'
color1='#394747'
color2='#4C524E'
color3='#616D69'
color4='#AF592F'
color5='#77837B'
color6='#8B857A'
color7='#b1bcbd'
color8='#7b8384'
color9='#394747'
color10='#4C524E'
color11='#616D69'
color12='#AF592F'
color13='#77837B'
color14='#8B857A'
color15='#b1bcbd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
