username = '12126956825'
auth_type = 1
auth_data = 'QVFCVEJXVXd2Q3U3QVdoVHFBLVB5UThDcE8wc24wWUpfSVM0TWhUY2poa1lmX2VFek0tNXlFUGZLcFkxZzJra1VseG5IU2Q3N25EMXZuZmN2RmZ2UDZkWDdRY080cFpBOFF3S3ZZSWhLdFdoeGFKcFB3WWVDSzlMN25SMWFkQ2c5YVZIY3VDWmFXZ2U='
